"use client";

import { jsPDF } from "jspdf";

import {
  DocumentRecord,
  HotelSnapshot,
  InvoiceRecord,
  PaymentRecord,
  ReceiptRecord,
} from "@/lib/hotel-data";

function addHotelHeader(pdf: jsPDF, hotel: HotelSnapshot["hotel"], title: string) {
  pdf.setFillColor(21, 20, 17);
  pdf.rect(0, 0, 210, 42, "F");
  pdf.setTextColor(224, 183, 104);
  pdf.setFontSize(10);
  pdf.text("STAYPILOT HOTEL OS", 20, 15);
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.text(hotel.hotelName, 20, 27);
  pdf.setFontSize(10);
  pdf.setTextColor(190, 190, 184);
  pdf.text(`${hotel.location}  |  ${hotel.phone}  |  ${hotel.email}`, 20, 35);
  pdf.setTextColor(30, 30, 30);
  pdf.setFontSize(17);
  pdf.text(title, 20, 56);
}

export function exportInvoicePdf(hotel: HotelSnapshot["hotel"], invoice: InvoiceRecord) {
  const pdf = new jsPDF();
  const invoiceNumber = invoice.invoiceNumber ?? invoice.bookingCode;
  addHotelHeader(pdf, hotel, `Tax invoice ${invoiceNumber}`);
  pdf.setFontSize(10);
  pdf.text(`Guest: ${invoice.guestName}`, 20, 68);
  pdf.text(`Booking: ${invoice.bookingCode}`, 20, 75);
  pdf.text(`Room: ${invoice.roomNumber ?? "Not assigned"}`, 20, 82);
  pdf.text(`Issued: ${invoice.issuedAt}`, 120, 68);
  pdf.text(`Due: ${invoice.dueDate ?? "On receipt"}`, 120, 75);
  pdf.text(`Status: ${invoice.status}`, 120, 82);

  pdf.setDrawColor(220, 216, 205);
  pdf.line(20, 92, 190, 92);
  pdf.setFontSize(10);
  pdf.text("Description", 20, 101);
  pdf.text("Amount", 190, 101, { align: "right" });

  let y = 112;
  invoice.lineItems.forEach((item) => {
    pdf.text(item.label, 20, y);
    pdf.text(`AED ${item.amount.toFixed(2)}`, 160, y, { align: "right" });
    y += 10;
  });

  pdf.line(20, y, 190, y);
  y += 12;
  pdf.text(`Total: AED ${invoice.totalAmount.toFixed(2)}`, 20, y);
  y += 8;
  pdf.text(`Paid: AED ${invoice.paidAmount.toFixed(2)}`, 20, y);
  y += 8;
  pdf.text(`Balance: AED ${invoice.balanceAmount.toFixed(2)}`, 20, y);
  if (invoice.notes) {
    y += 14;
    pdf.setTextColor(90, 90, 90);
    pdf.text(`Notes: ${invoice.notes}`, 20, y, { maxWidth: 170 });
  }
  pdf.save(`${invoiceNumber}.pdf`);
}

export function exportReceiptPdf(
  hotel: HotelSnapshot["hotel"],
  receipt: ReceiptRecord,
  payment?: PaymentRecord,
) {
  const pdf = new jsPDF({ format: [80, 150], unit: "mm" });
  pdf.setFillColor(21, 20, 17);
  pdf.rect(0, 0, 80, 30, "F");
  pdf.setTextColor(224, 183, 104);
  pdf.setFontSize(8);
  pdf.text("STAYPILOT RECEIPT", 8, 10);
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(13);
  pdf.text(hotel.hotelName, 8, 19);
  pdf.setFontSize(7);
  pdf.text(hotel.location, 8, 25);

  pdf.setTextColor(30, 30, 30);
  pdf.setFontSize(10);
  pdf.text(receipt.receiptNumber, 8, 40);
  pdf.setFontSize(8);
  pdf.text(`Invoice: ${receipt.invoiceNumber}`, 8, 49);
  pdf.text(`Guest: ${receipt.guestName}`, 8, 56, { maxWidth: 64 });
  pdf.text(`Method: ${receipt.method.replaceAll("_", " ")}`, 8, 66);
  pdf.text(`Issued: ${receipt.issuedAt}`, 8, 73, { maxWidth: 64 });
  if (payment?.reference) {
    pdf.text(`Reference: ${payment.reference}`, 8, 83, { maxWidth: 64 });
  }
  pdf.setDrawColor(215, 210, 197);
  pdf.line(8, 94, 72, 94);
  pdf.setFontSize(8);
  pdf.text("Amount received", 8, 105);
  pdf.setFontSize(16);
  pdf.text(`AED ${receipt.amount.toFixed(2)}`, 8, 117);
  pdf.setFontSize(7);
  pdf.setTextColor(100, 100, 100);
  pdf.text("Generated by the property payment ledger.", 8, 135);
  pdf.save(`${receipt.receiptNumber}.pdf`);
}

export function exportDocumentPdf(hotel: HotelSnapshot["hotel"], document: DocumentRecord) {
  const pdf = new jsPDF();
  pdf.setFontSize(20);
  pdf.text(hotel.hotelName, 20, 20);
  pdf.setFontSize(12);
  pdf.text(document.title, 20, 34);
  pdf.text(`Type: ${document.type}`, 20, 44);
  pdf.text(`Reference: ${document.linkedRef}`, 20, 54);
  pdf.text(`Created: ${document.createdAt}`, 20, 64);
  pdf.save(`${document.title.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}
