import "server-only";

import type { HotelSnapshot, PaymentMethod } from "@/lib/hotel-data";
import { getDb } from "@/lib/db";

function dateOnly(value: Date) {
  return value.toISOString().slice(0, 10);
}

function stamp(value: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: "UTC",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(value);
}

export async function getHotelSnapshot(hotelId: string): Promise<HotelSnapshot> {
  const db = getDb();
  const hotel = await db.hotel.findUnique({
    where: { id: hotelId },
    include: {
      users: { orderBy: { createdAt: "desc" } },
      rooms: { include: { roomType: true }, orderBy: [{ floor: "asc" }, { roomNumber: "asc" }] },
      guests: { orderBy: { updatedAt: "desc" } },
      bookings: { orderBy: { createdAt: "desc" } },
      housekeepingTasks: { include: { room: { include: { roomType: true } } }, orderBy: { createdAt: "desc" } },
      maintenanceTickets: { include: { room: true, vendor: true }, orderBy: { createdAt: "desc" } },
      complaints: { include: { room: true }, orderBy: { createdAt: "desc" } },
      invoices: { include: { items: true }, orderBy: { issuedAt: "desc" } },
      payments: { include: { invoice: true }, orderBy: { processedAt: "desc" } },
      receipts: { orderBy: { issuedAt: "desc" } },
      policies: { where: { active: true }, orderBy: { updatedAt: "desc" } },
      roomCards: { include: { room: true }, orderBy: { createdAt: "desc" } },
      accessEvents: { include: { card: { include: { room: true } } }, orderBy: { occurredAt: "desc" }, take: 500 },
      blueprints: { include: { zones: { include: { room: true } } }, orderBy: { floor: "asc" } },
      paymentGateways: { orderBy: { createdAt: "asc" } },
      documents: { orderBy: { createdAt: "desc" } },
      notifications: { orderBy: { createdAt: "desc" }, take: 500 },
      auditLogs: { orderBy: { createdAt: "desc" }, take: 1000 },
      inventoryItems: { include: { vendor: true }, orderBy: { name: "asc" } },
      vendors: { orderBy: { name: "asc" } },
      groups: { include: { bookings: { select: { code: true } } }, orderBy: { createdAt: "desc" } },
      handovers: { orderBy: { createdAt: "desc" }, take: 500 },
      nightAudits: { orderBy: { businessDate: "desc" }, take: 365 },
      integrations: { orderBy: { createdAt: "asc" } },
    },
  });
  if (!hotel) throw new Error("HOTEL_NOT_FOUND");

  return {
    hotel: {
      hotelName: hotel.name,
      location: [hotel.city, hotel.country].filter(Boolean).join(", "),
      checkInTime: hotel.checkInTime,
      checkOutTime: hotel.checkOutTime,
      taxRate: Number(hotel.taxRate),
      timezone: hotel.timezone,
      phone: hotel.phone,
      email: hotel.email,
      theme: { mode: "dark", accent: hotel.themeAccent, surface: hotel.themeSurface, surfaceStrong: hotel.themeSurfaceStrong },
    },
    rooms: hotel.rooms.map((room) => ({
      id: room.id,
      roomNumber: room.roomNumber,
      roomType: room.roomType.name,
      floor: room.floor,
      status: room.status,
      capacity: room.capacity,
      guestName: room.guestName ?? undefined,
      nextBooking: room.nextBookingAt ? dateOnly(room.nextBookingAt) : undefined,
      housekeepingNote: room.housekeepingNote ?? undefined,
      outOfService: room.outOfService,
    })),
    guests: hotel.guests.map((guest) => ({
      id: guest.id,
      firstName: guest.firstName,
      lastName: guest.lastName,
      phone: guest.phone,
      email: guest.email,
      nationality: guest.nationality,
      vipStatus: guest.vipStatus,
      preferences: Array.isArray(guest.preferences) ? (guest.preferences as string[]) : [],
      notes: guest.notes,
      stayCount: guest.stayCount,
      loyaltyPoints: guest.loyaltyPoints,
      loyaltyTier: guest.loyaltyTier as "BRONZE" | "SILVER" | "GOLD" | "PLATINUM",
      companyName: guest.companyName ?? undefined,
      blacklisted: guest.blacklisted,
    })),
    bookings: hotel.bookings.map((booking) => ({
      id: booking.id,
      code: booking.code,
      guestId: booking.guestId,
      guestName: booking.guestName,
      roomType: booking.roomTypeName,
      roomNumber: hotel.rooms.find((room) => room.id === booking.roomId)?.roomNumber,
      status: booking.status,
      source: booking.source,
      checkIn: dateOnly(booking.checkInAt),
      checkOut: dateOnly(booking.checkOutAt),
      paymentStatus: booking.paymentStatus,
      advancePaid: Number(booking.advancePaid),
      depositRequired: Number(booking.depositRequired),
      totalAmount: Number(booking.totalAmount),
      specialRequests: booking.specialRequests,
      companyName: booking.companyName ?? undefined,
      groupReservationId: booking.groupReservationId ?? undefined,
      cancellationReason: booking.cancellationReason ?? undefined,
    })),
    housekeeping: hotel.housekeepingTasks.map((task) => ({
      id: task.id,
      roomNumber: task.room.roomNumber,
      roomType: task.room.roomType.name,
      status: task.status === "CANCELLED" ? "PENDING" : task.status,
      priority: task.priority,
      checkoutTime: task.checkoutAt ? stamp(task.checkoutAt) : "Not set",
      nextCheckInTime: task.nextCheckInAt ? stamp(task.nextCheckInAt) : undefined,
      assignee: task.assignee,
      checklistComplete: task.checklistComplete,
    })),
    maintenance: hotel.maintenanceTickets.map((ticket) => ({
      id: ticket.id,
      roomNumber: ticket.room?.roomNumber,
      title: ticket.title,
      category: ticket.category,
      priority: ticket.priority,
      status: ticket.status,
      assignee: ticket.assignee,
      description: ticket.description,
      vendorName: ticket.vendor?.name,
    })),
    complaints: hotel.complaints.map((complaint) => ({
      id: complaint.id,
      guestName: complaint.guestName,
      roomNumber: complaint.room?.roomNumber,
      category: complaint.category,
      priority: complaint.priority,
      status: complaint.status,
      department: complaint.department,
      message: complaint.message,
    })),
    invoices: hotel.invoices.map((invoice) => ({
      id: invoice.id,
      invoiceNumber: invoice.invoiceNumber,
      bookingCode: invoice.bookingCode,
      guestName: invoice.guestName,
      guestEmail: invoice.guestEmail ?? undefined,
      roomNumber: invoice.roomNumber ?? undefined,
      totalAmount: Number(invoice.totalAmount),
      paidAmount: Number(invoice.paidAmount),
      balanceAmount: Number(invoice.balanceAmount),
      status: invoice.status === "VOID" ? "UNPAID" : invoice.status,
      lineItems: invoice.items.map((item) => ({ label: item.label, amount: Number(item.amount) })),
      issuedAt: stamp(invoice.issuedAt),
      dueDate: invoice.dueAt ? dateOnly(invoice.dueAt) : undefined,
      notes: invoice.notes ?? undefined,
      currency: invoice.currency,
    })),
    payments: hotel.payments.map((payment) => ({
      id: payment.id,
      invoiceId: payment.invoiceId,
      invoiceNumber: payment.invoice.invoiceNumber,
      receiptNumber: payment.receiptNumber,
      guestName: payment.guestName,
      amount: Number(payment.amount),
      method: payment.method as PaymentMethod,
      status: payment.status === "FAILED" ? "REFUNDED" : payment.status,
      reference: payment.reference,
      processedAt: stamp(payment.processedAt),
      processedBy: payment.processedBy,
    })),
    receipts: hotel.receipts.map((receipt) => ({
      id: receipt.id,
      receiptNumber: receipt.receiptNumber,
      paymentId: receipt.paymentId,
      invoiceId: receipt.invoiceId,
      invoiceNumber: receipt.invoiceNumber,
      guestName: receipt.guestName,
      amount: Number(receipt.amount),
      method: receipt.method as PaymentMethod,
      issuedAt: stamp(receipt.issuedAt),
    })),
    policies: hotel.policies.map((policy) => ({ id: policy.id, title: policy.title, category: policy.category, content: policy.content })),
    staff: hotel.users.map((user) => ({ id: user.id, name: user.name, role: user.role, shift: user.shiftLabel ?? "Unassigned", load: user.workload ?? "No active allocation" })),
    users: hotel.users.map((user) => ({ id: user.id, name: user.name, email: user.email, role: user.role, active: user.status === "ACTIVE", status: user.status, mfaEnabled: user.mfaEnabled })),
    roomCards: hotel.roomCards.map((card) => ({ id: card.id, roomNumber: card.room.roomNumber, guestName: card.guestName ?? undefined, status: card.status, accessType: card.accessType, issuedAt: card.issuedAt ? stamp(card.issuedAt) : undefined })),
    nfcEvents: hotel.accessEvents.map((event) => ({ id: event.id, cardId: event.cardId, roomNumber: event.card.room.roomNumber, guestName: event.card.guestName ?? undefined, event: event.event, location: event.location, occurredAt: stamp(event.occurredAt) })),
    blueprints: hotel.blueprints.map((blueprint) => ({ id: blueprint.id, name: blueprint.name, floor: blueprint.floor, updatedAt: stamp(blueprint.updatedAt), zones: blueprint.zones.map((zone) => ({ id: zone.id, label: zone.label, type: zone.type, linkedRoomNumber: zone.room?.roomNumber })) })),
    paymentGateways: hotel.paymentGateways.map((gateway) => ({ id: gateway.id, name: gateway.name, method: gateway.method as PaymentMethod, enabled: gateway.enabled, status: gateway.status, settlementWindow: gateway.settlementWindow })),
    documents: hotel.documents.map((document) => ({ id: document.id, title: document.title, type: document.type, linkedRef: document.linkedRef, createdAt: stamp(document.createdAt) })),
    notifications: hotel.notifications.map((notification) => ({ id: notification.id, title: notification.title, message: notification.message, severity: notification.severity, audience: notification.audience as HotelSnapshot["notifications"][number]["audience"], read: Boolean(notification.readAt), createdAt: stamp(notification.createdAt) })),
    auditLogs: hotel.auditLogs.map((log) => ({ id: log.id, action: log.action, actor: log.actorName, target: log.target, createdAt: stamp(log.createdAt) })),
    inventory: hotel.inventoryItems.map((item) => ({ id: item.id, name: item.name, category: item.category, stockOnHand: item.stockOnHand, reorderLevel: item.reorderLevel, vendorName: item.vendor?.name })),
    vendors: hotel.vendors.map((vendor) => ({ id: vendor.id, name: vendor.name, category: vendor.category, contact: vendor.contact, sla: vendor.sla })),
    groupReservations: hotel.groups.map((group) => ({ id: group.id, groupName: group.groupName, bookingCodes: group.bookings.map((booking) => booking.code), companyName: group.companyName ?? undefined, roomCount: group.roomCount })),
    handovers: hotel.handovers.map((handover) => ({ id: handover.id, department: handover.department, note: handover.note, author: handover.author, createdAt: stamp(handover.createdAt) })),
    nightAudits: hotel.nightAudits.map((audit) => ({ id: audit.id, businessDate: dateOnly(audit.businessDate), status: audit.status, summary: audit.summary, createdAt: stamp(audit.createdAt) })),
    integrations: hotel.integrations.map((integration) => ({ id: integration.id, name: integration.name, type: integration.type, enabled: integration.enabled, status: integration.status })),
  };
}
