import "server-only";

import type { HotelSnapshot, PaymentMethod } from "@/lib/hotel-data";
import { getDb } from "@/lib/db";

function dateOnly(value: Date) {
  return value.toISOString().slice(0, 10);
}

function stamp(value: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: "UTC",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(value);
}

export async function getHotelSnapshot(hotelId: string): Promise<HotelSnapshot> {
  const db = getDb();
  const hotel = await db.hotel.findUnique({
    where: { id: hotelId },
    include: {
      users: { orderBy: { createdAt: "desc" } },
      propertyAccess: { where: { active: true }, include: { user: true }, orderBy: { createdAt: "desc" } },
      rooms: { include: { roomType: true }, orderBy: [{ floor: "asc" }, { roomNumber: "asc" }] },
      guests: { orderBy: { updatedAt: "desc" } },
      bookings: { orderBy: { createdAt: "desc" } },
      housekeepingTasks: { include: { room: { include: { roomType: true } } }, orderBy: { createdAt: "desc" } },
      maintenanceTickets: { include: { room: true, vendor: true }, orderBy: { createdAt: "desc" } },
      complaints: { include: { room: true }, orderBy: { createdAt: "desc" } },
      invoices: { include: { items: true }, orderBy: { issuedAt: "desc" } },
      payments: { include: { invoice: true }, orderBy: { processedAt: "desc" } },
      paymentRequests: { orderBy: { createdAt: "desc" }, take: 200 },
      cashierShifts: { orderBy: { openedAt: "desc" }, take: 100 },
      cashMovements: { orderBy: { createdAt: "desc" }, take: 500 },
      creditNotes: { orderBy: { issuedAt: "desc" }, take: 500 },
      reconciliations: { orderBy: { completedAt: "desc" }, take: 200 },
      receipts: { orderBy: { issuedAt: "desc" } },
      policies: { where: { active: true }, orderBy: { updatedAt: "desc" } },
      roomCards: { include: { room: true }, orderBy: { createdAt: "desc" } },
      accessEvents: { include: { card: { include: { room: true } } }, orderBy: { occurredAt: "desc" }, take: 500 },
      blueprints: { include: { zones: { include: { room: true } } }, orderBy: { floor: "asc" } },
      paymentGateways: { orderBy: { createdAt: "asc" } },
      documents: { select: { id: true, title: true, type: true, linkedRef: true, fileName: true, mimeType: true, sizeBytes: true, content: false, storageKey: true, createdAt: true }, orderBy: { createdAt: "desc" } },
      documentTemplates: { orderBy: { updatedAt: "desc" } },
      communications: { orderBy: { createdAt: "desc" }, take: 500 },
      notifications: { orderBy: { createdAt: "desc" }, take: 500 },
      auditLogs: { orderBy: { createdAt: "desc" }, take: 1000 },
      inventoryItems: { include: { vendor: true }, orderBy: { name: "asc" } },
      operationalTasks: { orderBy: [{ status: "asc" }, { dueAt: "asc" }, { createdAt: "desc" }], take: 500 },
      purchaseOrders: { include: { vendor: true, lines: { include: { inventoryItem: true } } }, orderBy: { createdAt: "desc" }, take: 300 },
      inventoryMovements: { include: { inventoryItem: true }, orderBy: { createdAt: "desc" }, take: 1000 },
      incidents: { include: { room: true }, orderBy: { occurredAt: "desc" }, take: 500 },
      lostFoundItems: { include: { room: true }, orderBy: { foundAt: "desc" }, take: 500 },
      vendors: { orderBy: { name: "asc" } },
      groups: { include: { bookings: { select: { code: true } } }, orderBy: { createdAt: "desc" } },
      handovers: { orderBy: { createdAt: "desc" }, take: 500 },
      nightAudits: { orderBy: { businessDate: "desc" }, take: 365 },
      integrations: { orderBy: { createdAt: "asc" } },
      nfcDevices: { include: { _count: { select: { commands: { where: { status: { in: ["QUEUED", "CLAIMED"] } } } } } }, orderBy: { createdAt: "asc" } },
      integrationSyncs: { orderBy: { createdAt: "desc" }, take: 500 },
      outlets: { orderBy: { name: "asc" } },
      outletOrders: { include: { outlet: true, lines: true }, orderBy: { createdAt: "desc" }, take: 500 },
      eventBookings: { orderBy: { startsAt: "asc" }, take: 500 },
      serviceAppointments: { include: { room: true }, orderBy: { startsAt: "asc" }, take: 500 },
      transportRequests: { orderBy: { pickupAt: "asc" }, take: 500 },
    },
  });
  if (!hotel) throw new Error("HOTEL_NOT_FOUND");

  return {
    hotel: {
      hotelName: hotel.name,
      location: [hotel.city, hotel.country].filter(Boolean).join(", "),
      checkInTime: hotel.checkInTime,
      checkOutTime: hotel.checkOutTime,
      taxRate: Number(hotel.taxRate),
      timezone: hotel.timezone,
      phone: hotel.phone,
      email: hotel.email,
      theme: { mode: "dark", accent: hotel.themeAccent, surface: hotel.themeSurface, surfaceStrong: hotel.themeSurfaceStrong },
    },
    rooms: hotel.rooms.map((room) => ({
      id: room.id,
      roomNumber: room.roomNumber,
      roomType: room.roomType.name,
      floor: room.floor,
      status: room.status,
      capacity: room.capacity,
      guestName: room.guestName ?? undefined,
      nextBooking: room.nextBookingAt ? dateOnly(room.nextBookingAt) : undefined,
      housekeepingNote: room.housekeepingNote ?? undefined,
      outOfService: room.outOfService,
    })),
    guests: hotel.guests.map((guest) => ({
      id: guest.id,
      firstName: guest.firstName,
      lastName: guest.lastName,
      phone: guest.phone,
      email: guest.email,
      nationality: guest.nationality,
      vipStatus: guest.vipStatus,
      preferences: Array.isArray(guest.preferences) ? (guest.preferences as string[]) : [],
      notes: guest.notes,
      stayCount: guest.stayCount,
      loyaltyPoints: guest.loyaltyPoints,
      loyaltyTier: guest.loyaltyTier as "BRONZE" | "SILVER" | "GOLD" | "PLATINUM",
      companyName: guest.companyName ?? undefined,
      blacklisted: guest.blacklisted,
    })),
    bookings: hotel.bookings.map((booking) => ({
      id: booking.id,
      code: booking.code,
      guestId: booking.guestId,
      guestName: booking.guestName,
      roomType: booking.roomTypeName,
      roomNumber: hotel.rooms.find((room) => room.id === booking.roomId)?.roomNumber,
      status: booking.status,
      source: booking.source,
      checkIn: dateOnly(booking.checkInAt),
      checkOut: dateOnly(booking.checkOutAt),
      paymentStatus: booking.paymentStatus,
      advancePaid: Number(booking.advancePaid),
      depositRequired: Number(booking.depositRequired),
      totalAmount: Number(booking.totalAmount),
      specialRequests: booking.specialRequests,
      companyName: booking.companyName ?? undefined,
      groupReservationId: booking.groupReservationId ?? undefined,
      cancellationReason: booking.cancellationReason ?? undefined,
    })),
    housekeeping: hotel.housekeepingTasks.map((task) => ({
      id: task.id,
      roomNumber: task.room.roomNumber,
      roomType: task.room.roomType.name,
      status: task.status === "CANCELLED" ? "PENDING" : task.status,
      priority: task.priority,
      checkoutTime: task.checkoutAt ? stamp(task.checkoutAt) : "Not set",
      nextCheckInTime: task.nextCheckInAt ? stamp(task.nextCheckInAt) : undefined,
      assignee: task.assignee,
      checklistComplete: task.checklistComplete,
    })),
    maintenance: hotel.maintenanceTickets.map((ticket) => ({
      id: ticket.id,
      roomNumber: ticket.room?.roomNumber,
      title: ticket.title,
      category: ticket.category,
      priority: ticket.priority,
      status: ticket.status,
      assignee: ticket.assignee,
      description: ticket.description,
      vendorName: ticket.vendor?.name,
    })),
    complaints: hotel.complaints.map((complaint) => ({
      id: complaint.id,
      guestName: complaint.guestName,
      roomNumber: complaint.room?.roomNumber,
      category: complaint.category,
      priority: complaint.priority,
      status: complaint.status,
      department: complaint.department,
      message: complaint.message,
    })),
    invoices: hotel.invoices.map((invoice) => ({
      id: invoice.id,
      invoiceNumber: invoice.invoiceNumber,
      bookingCode: invoice.bookingCode,
      guestName: invoice.guestName,
      guestEmail: invoice.guestEmail ?? undefined,
      roomNumber: invoice.roomNumber ?? undefined,
      totalAmount: Number(invoice.totalAmount),
      paidAmount: Number(invoice.paidAmount),
      balanceAmount: Number(invoice.balanceAmount),
      status: invoice.status === "VOID" ? "UNPAID" : invoice.status,
      lineItems: invoice.items.map((item) => ({ label: item.label, amount: Number(item.amount) })),
      issuedAt: stamp(invoice.issuedAt),
      dueDate: invoice.dueAt ? dateOnly(invoice.dueAt) : undefined,
      notes: invoice.notes ?? undefined,
      currency: invoice.currency,
    })),
    payments: hotel.payments.map((payment) => ({
      id: payment.id,
      invoiceId: payment.invoiceId,
      invoiceNumber: payment.invoice.invoiceNumber,
      receiptNumber: payment.receiptNumber,
      guestName: payment.guestName,
      amount: Number(payment.amount),
      method: payment.method as PaymentMethod,
      status: payment.status === "FAILED" ? "REFUNDED" : payment.status,
      amountRefunded: Number(payment.amountRefunded),
      provider: payment.provider,
      reference: payment.reference,
      processedAt: stamp(payment.processedAt),
      processedBy: payment.processedBy,
    })),
    paymentRequests: hotel.paymentRequests.map((request) => ({
      id: request.id,
      invoiceId: request.invoiceId,
      provider: request.provider,
      amount: Number(request.amount),
      currency: request.currency,
      status: request.status,
      checkoutUrl: request.checkoutUrl ?? undefined,
      createdAt: stamp(request.createdAt),
    })),
    cashierShifts: hotel.cashierShifts.map((shift) => ({
      id: shift.id,
      openedBy: shift.openedBy,
      openingFloat: Number(shift.openingFloat),
      expectedCash: Number(shift.expectedCash),
      closingCash: shift.closingCash == null ? undefined : Number(shift.closingCash),
      variance: shift.variance == null ? undefined : Number(shift.variance),
      status: shift.status,
      openedAt: stamp(shift.openedAt),
      closedAt: shift.closedAt ? stamp(shift.closedAt) : undefined,
    })),
    cashMovements: hotel.cashMovements.map((movement) => ({
      id: movement.id,
      shiftId: movement.shiftId,
      type: movement.type,
      amount: Number(movement.amount),
      reference: movement.reference ?? undefined,
      note: movement.note ?? undefined,
      createdBy: movement.createdBy,
      createdAt: stamp(movement.createdAt),
    })),
    creditNotes: hotel.creditNotes.map((note) => ({
      id: note.id,
      invoiceId: note.invoiceId,
      creditNoteNumber: note.creditNoteNumber,
      amount: Number(note.amount),
      reason: note.reason,
      issuedBy: note.issuedBy,
      issuedAt: stamp(note.issuedAt),
    })),
    reconciliations: hotel.reconciliations.map((run) => ({
      id: run.id,
      method: run.method as PaymentMethod,
      provider: run.provider,
      periodStart: stamp(run.periodStart),
      periodEnd: stamp(run.periodEnd),
      expectedAmount: Number(run.expectedAmount),
      actualAmount: Number(run.actualAmount),
      variance: Number(run.variance),
      status: run.status,
      completedBy: run.completedBy,
      completedAt: stamp(run.completedAt),
    })),
    receipts: hotel.receipts.map((receipt) => ({
      id: receipt.id,
      receiptNumber: receipt.receiptNumber,
      paymentId: receipt.paymentId,
      invoiceId: receipt.invoiceId,
      invoiceNumber: receipt.invoiceNumber,
      guestName: receipt.guestName,
      amount: Number(receipt.amount),
      method: receipt.method as PaymentMethod,
      issuedAt: stamp(receipt.issuedAt),
    })),
    policies: hotel.policies.map((policy) => ({ id: policy.id, title: policy.title, category: policy.category, content: policy.content })),
    staff: hotel.propertyAccess.map((access) => ({ id: access.user.id, name: access.user.name, role: access.role, shift: access.user.shiftLabel ?? "Unassigned", load: access.user.workload ?? "No active allocation" })),
    users: hotel.propertyAccess.map((access) => ({ id: access.user.id, name: access.user.name, email: access.user.email, role: access.role, active: access.user.status === "ACTIVE", status: access.user.status, mfaEnabled: access.user.mfaEnabled })),
    roomCards: hotel.roomCards.map((card) => ({ id: card.id, roomNumber: card.room.roomNumber, guestName: card.guestName ?? undefined, status: card.status, accessType: card.accessType, issuedAt: card.issuedAt ? stamp(card.issuedAt) : undefined })),
    nfcEvents: hotel.accessEvents.map((event) => ({ id: event.id, cardId: event.cardId, roomNumber: event.card.room.roomNumber, guestName: event.card.guestName ?? undefined, event: event.event, location: event.location, occurredAt: stamp(event.occurredAt) })),
    blueprints: hotel.blueprints.map((blueprint) => ({ id: blueprint.id, name: blueprint.name, floor: blueprint.floor, updatedAt: stamp(blueprint.updatedAt), zones: blueprint.zones.map((zone) => ({ id: zone.id, label: zone.label, type: zone.type, linkedRoomNumber: zone.room?.roomNumber })) })),
    paymentGateways: hotel.paymentGateways.map((gateway) => ({ id: gateway.id, name: gateway.name, method: gateway.method as PaymentMethod, enabled: gateway.enabled, status: gateway.status, settlementWindow: gateway.settlementWindow })),
    documents: hotel.documents.map((document) => ({ id: document.id, title: document.title, type: document.type, linkedRef: document.linkedRef, createdAt: stamp(document.createdAt), fileName: document.fileName ?? undefined, mimeType: document.mimeType ?? undefined, sizeBytes: document.sizeBytes ?? undefined, downloadable: Boolean(document.storageKey || document.fileName) })),
    documentTemplates: hotel.documentTemplates.map((template) => ({ id: template.id, name: template.name, type: template.type, subject: template.subject ?? undefined, content: template.content, active: template.active, createdBy: template.createdBy, updatedAt: stamp(template.updatedAt) })),
    communications: hotel.communications.map((communication) => ({ id: communication.id, channel: communication.channel, recipient: communication.recipient, subject: communication.subject ?? undefined, body: communication.body, status: communication.status, provider: communication.provider ?? undefined, linkedRef: communication.linkedRef ?? undefined, error: communication.error ?? undefined, createdBy: communication.createdBy, createdAt: stamp(communication.createdAt) })),
    notifications: hotel.notifications.map((notification) => ({ id: notification.id, title: notification.title, message: notification.message, severity: notification.severity, audience: notification.audience as HotelSnapshot["notifications"][number]["audience"], read: Boolean(notification.readAt), createdAt: stamp(notification.createdAt) })),
    auditLogs: hotel.auditLogs.map((log) => ({ id: log.id, action: log.action, actor: log.actorName, target: log.target, createdAt: stamp(log.createdAt) })),
    inventory: hotel.inventoryItems.map((item) => ({ id: item.id, name: item.name, category: item.category, stockOnHand: item.stockOnHand, reorderLevel: item.reorderLevel, vendorName: item.vendor?.name })),
    operationalTasks: hotel.operationalTasks.map((task) => ({ id: task.id, department: task.department, title: task.title, description: task.description, priority: task.priority, status: task.status, assignee: task.assignee, dueAt: task.dueAt ? stamp(task.dueAt) : undefined, createdBy: task.createdBy, createdAt: stamp(task.createdAt) })),
    purchaseOrders: hotel.purchaseOrders.map((order) => ({ id: order.id, poNumber: order.poNumber, vendorId: order.vendorId, vendorName: order.vendor.name, status: order.status, totalAmount: Number(order.totalAmount), notes: order.notes ?? undefined, requestedBy: order.requestedBy, createdAt: stamp(order.createdAt), lines: order.lines.map((line) => ({ id: line.id, inventoryItemId: line.inventoryItemId, itemName: line.inventoryItem.name, quantityOrdered: line.quantityOrdered, quantityReceived: line.quantityReceived, unitCost: Number(line.unitCost) })) })),
    inventoryMovements: hotel.inventoryMovements.map((movement) => ({ id: movement.id, inventoryItemId: movement.inventoryItemId, itemName: movement.inventoryItem.name, type: movement.type, quantityDelta: movement.quantityDelta, resultingStock: movement.resultingStock, reference: movement.reference ?? undefined, note: movement.note ?? undefined, recordedBy: movement.recordedBy, createdAt: stamp(movement.createdAt) })),
    incidents: hotel.incidents.map((incident) => ({ id: incident.id, roomNumber: incident.room?.roomNumber, type: incident.type, title: incident.title, description: incident.description, severity: incident.severity, status: incident.status, reportedBy: incident.reportedBy, assignedTo: incident.assignedTo ?? undefined, occurredAt: stamp(incident.occurredAt) })),
    lostFound: hotel.lostFoundItems.map((item) => ({ id: item.id, itemCode: item.itemCode, roomNumber: item.room?.roomNumber, category: item.category, description: item.description, foundLocation: item.foundLocation, storageLocation: item.storageLocation ?? undefined, status: item.status, guestName: item.guestName ?? undefined, guestContact: item.guestContact ?? undefined, foundAt: stamp(item.foundAt), recordedBy: item.recordedBy })),
    vendors: hotel.vendors.map((vendor) => ({ id: vendor.id, name: vendor.name, category: vendor.category, contact: vendor.contact, sla: vendor.sla })),
    groupReservations: hotel.groups.map((group) => ({ id: group.id, groupName: group.groupName, bookingCodes: group.bookings.map((booking) => booking.code), companyName: group.companyName ?? undefined, roomCount: group.roomCount })),
    handovers: hotel.handovers.map((handover) => ({ id: handover.id, department: handover.department, note: handover.note, author: handover.author, createdAt: stamp(handover.createdAt) })),
    nightAudits: hotel.nightAudits.map((audit) => ({ id: audit.id, businessDate: dateOnly(audit.businessDate), status: audit.status, summary: audit.summary, createdAt: stamp(audit.createdAt) })),
    integrations: hotel.integrations.map((integration) => ({ id: integration.id, name: integration.name, type: integration.type, enabled: integration.enabled, status: integration.status })),
    nfcDevices: hotel.nfcDevices.map((device) => ({ id: device.id, name: device.name, deviceCode: device.deviceCode, location: device.location, provider: device.provider, status: device.lastHeartbeat && device.lastHeartbeat > new Date(Date.now() - 120_000) ? device.status : "OFFLINE", firmware: device.firmware ?? undefined, lastHeartbeat: device.lastHeartbeat ? stamp(device.lastHeartbeat) : undefined, pendingCommands: device._count.commands })),
    integrationSyncs: hotel.integrationSyncs.map((sync) => ({ id: sync.id, provider: sync.provider, operation: sync.operation, direction: sync.direction, externalId: sync.externalId, status: sync.status, error: sync.error ?? undefined, processedAt: sync.processedAt ? stamp(sync.processedAt) : undefined, createdAt: stamp(sync.createdAt) })),
    outlets: hotel.outlets.map((outlet) => ({ id: outlet.id, name: outlet.name, type: outlet.type, location: outlet.location ?? undefined, active: outlet.active })),
    outletOrders: hotel.outletOrders.map((order) => ({ id: order.id, outletId: order.outletId, outletName: order.outlet.name, orderNumber: order.orderNumber, guestName: order.guestName ?? undefined, roomNumber: order.roomNumber ?? undefined, invoiceId: order.invoiceId ?? undefined, status: order.status, totalAmount: Number(order.totalAmount), notes: order.notes ?? undefined, openedBy: order.openedBy, createdAt: stamp(order.createdAt), lines: order.lines.map((line) => ({ id: line.id, label: line.label, quantity: Number(line.quantity), unitAmount: Number(line.unitAmount), amount: Number(line.amount) })) })),
    eventBookings: hotel.eventBookings.map((event) => ({ id: event.id, eventCode: event.eventCode, eventName: event.eventName, contactName: event.contactName, contactEmail: event.contactEmail ?? undefined, contactPhone: event.contactPhone ?? undefined, venue: event.venue, attendees: event.attendees, startsAt: stamp(event.startsAt), endsAt: stamp(event.endsAt), status: event.status, estimatedValue: Number(event.estimatedValue), depositPaid: Number(event.depositPaid), notes: event.notes ?? undefined })),
    serviceAppointments: hotel.serviceAppointments.map((appointment) => ({ id: appointment.id, appointmentCode: appointment.appointmentCode, department: appointment.department, serviceName: appointment.serviceName, guestName: appointment.guestName, guestContact: appointment.guestContact ?? undefined, roomNumber: appointment.room?.roomNumber, invoiceId: appointment.invoiceId ?? undefined, staffName: appointment.staffName ?? undefined, startsAt: stamp(appointment.startsAt), endsAt: stamp(appointment.endsAt), status: appointment.status, chargeAmount: Number(appointment.chargeAmount), notes: appointment.notes ?? undefined })),
    transportRequests: hotel.transportRequests.map((request) => ({ id: request.id, requestCode: request.requestCode, guestName: request.guestName, guestContact: request.guestContact ?? undefined, pickupLocation: request.pickupLocation, dropoffLocation: request.dropoffLocation, pickupAt: stamp(request.pickupAt), flightNumber: request.flightNumber ?? undefined, vehicleType: request.vehicleType ?? undefined, driverName: request.driverName ?? undefined, driverContact: request.driverContact ?? undefined, status: request.status, chargeAmount: Number(request.chargeAmount), notes: request.notes ?? undefined })),
  };
}
