"use client";

import { useState } from "react";

import { AppShell } from "@/components/app-shell";
import { CustomSelect } from "@/components/custom-select";
import { EmptyState } from "@/components/empty-state";
import { StatusBadge } from "@/components/status-badge";
import { useHotel } from "@/components/hotel-provider";

const inOneHour = () => new Date(Date.now() + 3_600_000).toISOString().slice(0, 16);
const inTwoHours = () => new Date(Date.now() + 7_200_000).toISOString().slice(0, 16);

export default function DepartmentsPage() {
  const { state, createOutlet, createOutletOrder, updateOutletOrderStatus, createEventBooking, updateEventBookingStatus, createServiceAppointment, updateServiceAppointmentStatus, createTransportRequest, updateTransportRequestStatus } = useHotel();
  const [view, setView] = useState("OUTLETS");
  const [message, setMessage] = useState("");
  const [outlet, setOutlet] = useState({ name: "", type: "RESTAURANT", location: "" });
  const [order, setOrder] = useState({ outletId: state.outlets[0]?.id ?? "", invoiceId: "", guestName: "", roomNumber: "", label: "", quantity: 1, unitAmount: 0, notes: "" });
  const [event, setEvent] = useState({ eventName: "", contactName: "", contactEmail: "", contactPhone: "", venue: "", attendees: 1, startsAt: inOneHour(), endsAt: inTwoHours(), estimatedValue: 0, notes: "" });
  const [appointment, setAppointment] = useState({ department: "SPA", serviceName: "", guestName: "", guestContact: "", roomNumber: "", invoiceId: "", staffName: "", startsAt: inOneHour(), endsAt: inTwoHours(), chargeAmount: 0, notes: "" });
  const [transport, setTransport] = useState({ guestName: "", guestContact: "", pickupLocation: "", dropoffLocation: "", pickupAt: inOneHour(), flightNumber: "", vehicleType: "SEDAN", chargeAmount: 0, notes: "" });
  const tabs = [["OUTLETS", "Dining & room service"], ["EVENTS", "Events"], ["SERVICES", "Spa & services"], ["TRANSPORT", "Transport"]];
  const submit = async (work: Promise<{ ok: boolean; message: string }>) => { const result = await work; setMessage(result.message); return result.ok; };

  return <AppShell activeHref="/departments" eyebrow="Departments" title="Hotel departments" description="Run dining, room service, events, guest appointments, and transport from one accountable operating console.">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {[["Open outlet orders", state.outletOrders.filter((item) => !["POSTED", "VOID"].includes(item.status)).length], ["Upcoming events", state.eventBookings.filter((item) => !["COMPLETED", "CANCELLED"].includes(item.status)).length], ["Appointments", state.serviceAppointments.filter((item) => !["COMPLETED", "CANCELLED", "NO_SHOW"].includes(item.status)).length], ["Transport queue", state.transportRequests.filter((item) => !["COMPLETED", "CANCELLED"].includes(item.status)).length]].map(([label, value]) => <div className="suite-card p-5" key={label}><p className="suite-label">{label}</p><p className="mt-3 font-mono text-3xl font-semibold">{value}</p></div>)}
    </section>
    <div className="mt-6 flex flex-wrap gap-2" role="tablist">{tabs.map(([value, label]) => <button key={value} type="button" onClick={() => setView(value)} className={view === value ? "suite-button suite-button-primary" : "suite-button suite-button-secondary"}>{label}</button>)}</div>
    {message ? <p className="mt-4 rounded-lg border border-border bg-card/60 px-4 py-3 text-sm text-muted-foreground">{message}</p> : null}

    {view === "OUTLETS" ? <section className="mt-6 grid gap-6 xl:grid-cols-[.75fr_1.25fr]">
      <div className="grid gap-6"><div className="suite-card p-6"><span className="suite-eyebrow">Configuration</span><h2 className="mt-3 text-xl font-semibold">Create outlet</h2><div className="mt-4 grid gap-3"><input className="suite-input" placeholder="Outlet name" value={outlet.name} onChange={(e) => setOutlet({ ...outlet, name: e.target.value })}/><CustomSelect value={outlet.type} onChange={(type) => setOutlet({ ...outlet, type })} options={["RESTAURANT", "ROOM_SERVICE", "BAR", "MINIBAR", "BANQUET"].map((value) => ({ value, label: value.replaceAll("_", " ") }))}/><input className="suite-input" placeholder="Location" value={outlet.location} onChange={(e) => setOutlet({ ...outlet, location: e.target.value })}/><button className="suite-button suite-button-primary" onClick={async () => { if (await submit(createOutlet(outlet))) setOutlet({ ...outlet, name: "", location: "" }); }}>Add outlet</button></div></div>
      <div className="suite-card p-6"><span className="suite-eyebrow">POS</span><h2 className="mt-3 text-xl font-semibold">Open guest order</h2><div className="mt-4 grid gap-3"><CustomSelect value={order.outletId} onChange={(outletId) => setOrder({ ...order, outletId })} options={state.outlets.filter((item) => item.active).map((item) => ({ value: item.id, label: item.name }))}/><CustomSelect value={order.invoiceId} onChange={(invoiceId) => { const invoice = state.invoices.find((item) => item.id === invoiceId); setOrder({ ...order, invoiceId, guestName: invoice?.guestName ?? order.guestName, roomNumber: invoice?.roomNumber ?? order.roomNumber }); }} options={[{ value: "", label: "No invoice selected" }, ...state.invoices.map((item) => ({ value: item.id, label: `${item.invoiceNumber} · ${item.guestName}` }))]}/><div className="grid grid-cols-2 gap-3"><input className="suite-input" placeholder="Guest" value={order.guestName} onChange={(e) => setOrder({ ...order, guestName: e.target.value })}/><input className="suite-input" placeholder="Room" value={order.roomNumber} onChange={(e) => setOrder({ ...order, roomNumber: e.target.value })}/></div><input className="suite-input" placeholder="Item or service" value={order.label} onChange={(e) => setOrder({ ...order, label: e.target.value })}/><div className="grid grid-cols-2 gap-3"><input className="suite-input" type="number" min="1" value={order.quantity} onChange={(e) => setOrder({ ...order, quantity: Number(e.target.value) })}/><input className="suite-input" type="number" min="0" step="0.01" value={order.unitAmount} onChange={(e) => setOrder({ ...order, unitAmount: Number(e.target.value) })}/></div><button className="suite-button suite-button-primary" onClick={() => submit(createOutletOrder({ ...order, lines: [{ label: order.label, quantity: order.quantity, unitAmount: order.unitAmount }] }))}>Open order</button></div></div></div>
      <Queue title="Outlet order queue" empty="No outlet orders yet.">{state.outletOrders.map((item) => <article className="suite-subcard p-4" key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-primary">{item.orderNumber}</p><p className="mt-2 font-medium">{item.outletName} · {item.guestName || "Walk-in"}</p><p className="mt-1 text-xs text-muted-foreground">{item.lines.map((line) => `${line.quantity}× ${line.label}`).join(", ")} · {state.hotel.hotelName} {item.totalAmount.toFixed(2)}</p></div><StatusBadge value={item.status}/></div><div className="mt-3 flex flex-wrap gap-2">{item.status === "OPEN" ? <Action label="Prepare" onClick={() => submit(updateOutletOrderStatus(item.id, "PREPARING"))}/> : null}{item.status === "PREPARING" ? <Action label="Serve" onClick={() => submit(updateOutletOrderStatus(item.id, "SERVED"))}/> : null}{item.status === "SERVED" ? <Action label="Post to invoice" primary onClick={() => submit(updateOutletOrderStatus(item.id, "POSTED"))}/> : null}</div></article>)}</Queue>
    </section> : null}

    {view === "EVENTS" ? <DepartmentPanel title="Reserve event" fields={<><input className="suite-input" placeholder="Event name" value={event.eventName} onChange={(e) => setEvent({ ...event, eventName: e.target.value })}/><div className="grid grid-cols-2 gap-3"><input className="suite-input" placeholder="Contact name" value={event.contactName} onChange={(e) => setEvent({ ...event, contactName: e.target.value })}/><input className="suite-input" placeholder="Venue" value={event.venue} onChange={(e) => setEvent({ ...event, venue: e.target.value })}/></div><div className="grid grid-cols-2 gap-3"><input className="suite-input" type="datetime-local" value={event.startsAt} onChange={(e) => setEvent({ ...event, startsAt: e.target.value })}/><input className="suite-input" type="datetime-local" value={event.endsAt} onChange={(e) => setEvent({ ...event, endsAt: e.target.value })}/></div><div className="grid grid-cols-2 gap-3"><input className="suite-input" type="number" min="1" value={event.attendees} onChange={(e) => setEvent({ ...event, attendees: Number(e.target.value) })}/><input className="suite-input" type="number" min="0" placeholder="Estimated value" value={event.estimatedValue} onChange={(e) => setEvent({ ...event, estimatedValue: Number(e.target.value) })}/></div><button className="suite-button suite-button-primary" onClick={() => submit(createEventBooking(event))}>Reserve venue</button></>}><Queue title="Event pipeline" empty="No event bookings yet.">{state.eventBookings.map((item) => <RecordCard key={item.id} code={item.eventCode} title={`${item.eventName} · ${item.venue}`} detail={`${item.attendees} guests · ${item.startsAt}`} status={item.status} actions={item.status === "TENTATIVE" ? <Action label="Confirm" primary onClick={() => submit(updateEventBookingStatus(item.id, "CONFIRMED"))}/> : item.status === "CONFIRMED" ? <Action label="Start" onClick={() => submit(updateEventBookingStatus(item.id, "IN_PROGRESS"))}/> : item.status === "IN_PROGRESS" ? <Action label="Complete" primary onClick={() => submit(updateEventBookingStatus(item.id, "COMPLETED"))}/> : null}/>)}</Queue></DepartmentPanel> : null}

    {view === "SERVICES" ? <DepartmentPanel title="Book appointment" fields={<><div className="grid grid-cols-2 gap-3"><input className="suite-input" placeholder="Service" value={appointment.serviceName} onChange={(e) => setAppointment({ ...appointment, serviceName: e.target.value })}/><input className="suite-input" placeholder="Guest" value={appointment.guestName} onChange={(e) => setAppointment({ ...appointment, guestName: e.target.value })}/></div><div className="grid grid-cols-2 gap-3"><input className="suite-input" placeholder="Staff member" value={appointment.staffName} onChange={(e) => setAppointment({ ...appointment, staffName: e.target.value })}/><input className="suite-input" placeholder="Room" value={appointment.roomNumber} onChange={(e) => setAppointment({ ...appointment, roomNumber: e.target.value })}/></div><CustomSelect value={appointment.invoiceId} onChange={(invoiceId) => setAppointment({ ...appointment, invoiceId })} options={[{ value: "", label: "No invoice selected" }, ...state.invoices.map((item) => ({ value: item.id, label: `${item.invoiceNumber} · ${item.guestName}` }))]}/><div className="grid grid-cols-2 gap-3"><input className="suite-input" type="datetime-local" value={appointment.startsAt} onChange={(e) => setAppointment({ ...appointment, startsAt: e.target.value })}/><input className="suite-input" type="datetime-local" value={appointment.endsAt} onChange={(e) => setAppointment({ ...appointment, endsAt: e.target.value })}/></div><input className="suite-input" type="number" min="0" placeholder="Charge" value={appointment.chargeAmount} onChange={(e) => setAppointment({ ...appointment, chargeAmount: Number(e.target.value) })}/><button className="suite-button suite-button-primary" onClick={() => submit(createServiceAppointment(appointment))}>Book appointment</button></>}><Queue title="Service diary" empty="No appointments yet.">{state.serviceAppointments.map((item) => <RecordCard key={item.id} code={item.appointmentCode} title={`${item.serviceName} · ${item.guestName}`} detail={`${item.staffName || "Unassigned"} · ${item.startsAt}`} status={item.status} actions={item.status === "BOOKED" ? <Action label="Check in" primary onClick={() => submit(updateServiceAppointmentStatus(item.id, "CHECKED_IN"))}/> : item.status === "CHECKED_IN" ? <Action label="Start service" onClick={() => submit(updateServiceAppointmentStatus(item.id, "IN_SERVICE"))}/> : item.status === "IN_SERVICE" ? <Action label="Complete & post" primary onClick={() => submit(updateServiceAppointmentStatus(item.id, "COMPLETED"))}/> : null}/>)}</Queue></DepartmentPanel> : null}

    {view === "TRANSPORT" ? <DepartmentPanel title="Arrange transport" fields={<><div className="grid grid-cols-2 gap-3"><input className="suite-input" placeholder="Guest" value={transport.guestName} onChange={(e) => setTransport({ ...transport, guestName: e.target.value })}/><input className="suite-input" placeholder="Contact" value={transport.guestContact} onChange={(e) => setTransport({ ...transport, guestContact: e.target.value })}/></div><input className="suite-input" placeholder="Pickup" value={transport.pickupLocation} onChange={(e) => setTransport({ ...transport, pickupLocation: e.target.value })}/><input className="suite-input" placeholder="Drop-off" value={transport.dropoffLocation} onChange={(e) => setTransport({ ...transport, dropoffLocation: e.target.value })}/><div className="grid grid-cols-2 gap-3"><input className="suite-input" type="datetime-local" value={transport.pickupAt} onChange={(e) => setTransport({ ...transport, pickupAt: e.target.value })}/><input className="suite-input" placeholder="Flight number" value={transport.flightNumber} onChange={(e) => setTransport({ ...transport, flightNumber: e.target.value })}/></div><button className="suite-button suite-button-primary" onClick={() => submit(createTransportRequest(transport))}>Create transfer</button></>}><Queue title="Transport board" empty="No transport requests yet.">{state.transportRequests.map((item) => <RecordCard key={item.id} code={item.requestCode} title={`${item.guestName} · ${item.vehicleType || "Vehicle pending"}`} detail={`${item.pickupLocation} → ${item.dropoffLocation} · ${item.pickupAt}`} status={item.status} actions={item.status === "REQUESTED" ? <Action label="Confirm" primary onClick={() => submit(updateTransportRequestStatus(item.id, "CONFIRMED"))}/> : item.status === "CONFIRMED" ? <Action label="Dispatch driver" onClick={() => submit(updateTransportRequestStatus(item.id, "DISPATCHED", "Hotel Driver"))}/> : item.status === "DISPATCHED" ? <Action label="Complete" primary onClick={() => submit(updateTransportRequestStatus(item.id, "COMPLETED"))}/> : null}/>)}</Queue></DepartmentPanel> : null}
  </AppShell>;
}

function DepartmentPanel({ title, fields, children }: { title: string; fields: React.ReactNode; children: React.ReactNode }) { return <section className="mt-6 grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><div className="suite-card p-6"><span className="suite-eyebrow">Create</span><h2 className="mt-3 text-xl font-semibold">{title}</h2><div className="mt-4 grid gap-3">{fields}</div></div>{children}</section>; }
function Queue({ title, empty, children }: { title: string; empty: string; children: React.ReactNode }) { const rows = Array.isArray(children) ? children : [children]; return <div className="suite-card p-6"><span className="suite-eyebrow">Live queue</span><h2 className="mt-3 text-xl font-semibold">{title}</h2><div className="mt-4 grid gap-3">{rows.length && rows.some(Boolean) ? children : <EmptyState title={empty} description="New records will appear here with live status and accountable actions."/>}</div></div>; }
function Action({ label, primary, onClick }: { label: string; primary?: boolean; onClick: () => void }) { return <button type="button" className={primary ? "suite-button suite-button-primary" : "suite-button suite-button-secondary"} onClick={onClick}>{label}</button>; }
function RecordCard({ code, title, detail, status, actions }: { code: string; title: string; detail: string; status: string; actions: React.ReactNode }) { return <article className="suite-subcard p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-primary">{code}</p><p className="mt-2 font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><StatusBadge value={status}/></div>{actions ? <div className="mt-3 flex gap-2">{actions}</div> : null}</article>; }
